# Nome das Ações:
nome: Jogo da Cobra

# Controlador do tempo que será feito a atualização dos arquivos.
sobre:
  agendar:
    # atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar a lista de Actions (utilizada para testes de build).
fluxo_de_trabalho_dispatch:

# Regras
empregos:
  construir:
    executado: ubuntu-mais-recente
    passos:

      # Verifica o repositório em $GITHUB_WORKSHOP, para que seu trabalho possa acessá-lo
      - usa: ações/checkout@v2

      # Repositório que será utilizado para gerar os arquivos.
      - usa: Platane/snk@master
        id: cobra-gif
        com:
          github_user_name: SeuNomeDeUsuario # Substitua pelo seu nome de usuário real
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - executar: git status

      # Para as atualizações.
      - nome: Enviar alterações
        usa: ad-m/github-push-action@master
        com:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ramo: mestre
          força: verdadeiro

      - usa: crazy-max/ghaction-github-pages@v2.1.3
        com:
          # o branch de saída que mencionamos acima
          target_branch: saída
          build_dir: dist
        ambiente:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
